# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'tomoya-amachis-blog'

google-ID: ''

menu:
- {name: 'Blog', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/tomoyamachi'}
- {icon: 'twitter', link: 'https://twitter.com/tomoyamachi'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
